server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/students/**
        - id: faculty-service
          uri: lb://FACULTY-SERVICE
          predicates:
            - Path=/faculty/**
        - id: department-service
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
        - id: course-service
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/courses/**
        - id: enrollment-service
          uri: lb://ENROLLMENT-SERVICE
          predicates:
            - Path=/enrollments/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: api-gateway
    instance-id: ${spring.application.name}:${random.value}

jwt:
  secret: 5367566B5970337336763979244226452948404D635166546A576E5A72347537
